### PR TITLE
Update module for Django 2.0 compatibility

### PR DESCRIPTION
**Pull request by ajira86**

### CODE REVIEW

**Comment by ajira86** [comment]
Just a remark: BDItem.text value is now saved as binary string should we change something about that ?

**Comment by kyokenn** [comment]
> BDItem.text value is now saved as binary string

Is it Django or Radicale changes?

**Comment by ajira86** [comment]
I tried back to Django < 2 and the text field was saved again like before. (and didn't change Radicale module version)

**Comment by kyokenn** [comment]
Ok. I checked the tests, so that should not be a problem. Thanks for the PR.
I also fixed a test_project. I will push the changes after this PR.

**Pull request merged**
