### PR TITLE
Update to make it work again

### PR DESCRIPTION
**Pull request by mir06**
There were only some small changes to make the code work with `radicale>=3.1.2` (see the commits with the type `fix`).
The test data had to be adapted as well.
I updated the README to reflect the changes already done in `0.0.16.

And I ran `ruff check` and `ruff format` for a consistent formatting.

### CODE REVIEW

**Comment by kyokenn** [comment]
> And I ran ruff check and ruff format for a consistent formatting.

Please, don't do it. It makes PR huge for unnecessary changes like quotes replacement ' -> "
Thanks for the PR anyway. Which CalDAV/CardDAV clients did you used for testing this?

**Comment by mir06** [comment]
Sorry for the ruff. I just reverted to the previous commit.

**Comment by mir06** [comment]
I tested with thunderbird and evolution on the desktop but **not** with DAVx5 on the mobile.

**Comment by mir06** [comment]
Dear @kyokenn, any chance you will have a look at the MR?

**Comment by kyokenn** [comment]
Thanks for the MR!

**Pull request merged**
